# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "./applications"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "./api-tests"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories:
      - ".github/**/*"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - "./applications/**/*"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
