---
name: 'Configure Bruno env'

inputs:
  marketplace-port:
    required: true
    description: 'Marketplace api port'
  price-port:
    required: true
    description: 'Price api port'
  stock-port:
    required: true
    description: 'Stock api port'
  product-port:
    required: true
    description: 'Product api port'
runs:
  using: composite
  steps:

    - name: 'Configure Bruno env'
      env:
        marketplace-port: ${{ steps.evaluate-port.outputs.public-port }}
        price-port: ${{ steps.evaluate-port.outputs.public-port }}
        stock-port: ${{ steps.evaluate-port.outputs.public-port }}
        product-port: ${{ steps.evaluate-port.outputs.public-port }}
      shell: bash
      run: |
        sed -i 's/marketplace_port/${{ env.marketplace-port }}/g' ./api-tests/environments/ci.bru
        sed -i 's/price_port/${{ env.price-port }}/g' ./api-tests/environments/ci.bru
        sed -i 's/stock_port/${{ env.stock-port }}/g' ./api-tests/environments/ci.bru
        sed -i 's/product_port/${{ env.product-port }}/g' ./api-tests/environments/ci.bru
