name: eshop

services:

  product-api:
    container_name: "product-api"
    build:
      context: eshop-product
    ports:
      - "${PORT_BINDING_PRODUCT}8080"

  stock-api:
    container_name: "stock-api"
    build:
      context: eshop-stock
    ports:
      - "${PORT_BINDING_STOCK}8080"

  price-api:
    container_name: "price-api"
    build:
      context: eshop-price
    ports:
      - "${PORT_BINDING_PRICE}8080"
    environment:
      - PRICE_CLIENT_PRODUCT_URL=http://product-api:8080

  marketplace-api:
    container_name: "marketplace-api"
    build:
      context: eshop-marketplace
    ports:
      - "${PORT_BINDING_MARKETPLACE}8080"
    environment:
      - MARKETPLACE_CLIENT_STOCK_URL=http://stock-api:8080
      - MARKETPLACE_CLIENT_PRICE_URL=http://price-api:8080
      - MARKETPLACE_CLIENT_PRODUCT_URL=http://product-api:8080
