name: eshop

services:

  catalog-api:
    container_name: "catalog-api"
    build:
      context: eshop-catalog
    ports:
      - "${PORT_BINDING_CATALOG}8080"

  price-api:
    container_name: "price-api"
    build:
      context: eshop-price
    ports:
      - "${PORT_BINDING_PRICE}8080"
    environment:
      - PRICE_CLIENT_CATALOG_URL=http://catalog-api:8080

  marketplace-api:
    container_name: "marketplace-api"
    build:
      context: eshop-marketplace
    ports:
      - "${PORT_BINDING_MARKETPLACE}8080"
    environment:
      - MARKETPLACE_CLIENT_PRICE_URL=http://price-api:8080
      - MARKETPLACE_CLIENT_CATALOG_URL=http://catalog-api:8080
