---
name: 'Configure Bruno env'
description: 'Configure Bruno environment with the correct ports for the APIs'

inputs:
  marketplace-port:
    required: true
    description: 'Marketplace api port'
  price-port:
    required: true
    description: 'Price api port'
  catalog-port:
    required: true
    description: 'Catalog api port'
runs:
  using: composite
  steps:

    - name: 'Configure Bruno env'
      shell: bash
      run: |
        sed -i 's/marketplace_port/${{ inputs.marketplace-port }}/g' ./api-tests/environments/ci.yml
        sed -i 's/price_port/${{ inputs.price-port }}/g' ./api-tests/environments/ci.yml
        sed -i 's/catalog_port/${{ inputs.catalog-port }}/g' ./api-tests/environments/ci.yml

