---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: eshop-app
  labels:
    app: product-api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
        env: dev
    spec:
      containers:
        - name: product-api
          image: deroffal/eshop-product:0.9
