---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  namespace: eshop-app
  labels:
    app: stock-api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
        env: dev
    spec:
      containers:
        - name: stock-api
          image: deroffal/eshop-stock:0.9
