---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-api
  namespace: eshop-app
  labels:
    app: price-api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-api
  template:
    metadata:
      labels:
        app: price-api
        env: dev
    spec:
      containers:
        - name: price-api
          image: deroffal/eshop-price:0.9
          envFrom:
            - configMapRef:
                name: price-cm
