---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-api
  namespace: eshop-app
  labels:
    app: marketplace-api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-api
  template:
    metadata:
      labels:
        app: marketplace-api
        env: dev
    spec:
      containers:
        - name: marketplace-api
          image: deroffal/eshop-marketplace:0.9
          env:
            - name: STOCK_API_URL
              value: http://stock.eshop-app.svc.cluster.local
            - name: PRICE_API_URL
              value: http://price.eshop-app.svc.cluster.local
            - name: PRODUCT_API_URL
              value: http://product.eshop-app.svc.cluster.local
