apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-cm
  namespace: eshop-app
data:
  OTEL_METRIC_EXPORT_INTERVAL: "15000"
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector.eshop-infra.svc.cluster.local:4317'
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
