apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-cm
  namespace: eshop-app
data:
  MARKETPLACE_CLIENT_PRICE_URL: 'http://price.eshop-app.svc.cluster.local'
  MARKETPLACE_CLIENT_CATALOG_URL: 'http://catalog.eshop-app.svc.cluster.local'
