---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-api
  namespace: eshop-app
  labels:
    app: price-api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-api
  template:
    metadata:
      labels:
        app: price-api
        env: dev
    spec:
      containers:
        - name: price-api
          image: deroffal/eshop-price:0.10-span
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/otel/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "price-api"
          envFrom:
            - configMapRef:
                name: price-cm
            - configMapRef:
                name: otel-cm
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi
          startupProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            periodSeconds: 5
            failureThreshold: 3
