receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger-server:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
#    metrics:
#      receivers: [otlp]
#      exporters: [debug]
#    logs:
#      receivers: [otlp]
#      exporters: [debug]
