
services:

  product-api:
    image: deroffal/eshop-product:0.7
    container_name: "product-api"
    ports:
      - "8081:8080"

  stock-api:
    image: deroffal/eshop-stock:0.7
    container_name: "stock-api"
    ports:
      - "8082:8080"

  price-api:
    image: deroffal/eshop-price:0.7
    container_name: "price-api"
    ports:
      - "8083:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Dproduct.api.url=http://product-api:8080

  marketplace-api:
    image: deroffal/eshop-marketplace:0.7
    container_name: "marketplace-api"
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Dproduct.api.url=http://product-api:8080 -Dstock.api.url=http://stock-api:8080 -Dprice.api.url=http://price-api:8080
