---
name: 'API tests'

on:
  workflow_dispatch:
  workflow_call:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: 'Build'
        working-directory: 'applications'
        run: ./mvnw clean package -DskipTests

      - name: 'Start apps'
        working-directory: 'applications'
        run: docker compose --env-file=../api-tests/.env.ci up --detach

      - name: 'Check deployment - marketplace'
        id: check-marketplace-deployment
        uses: ./.github/actions/check-api-deployment
        with:
          service-name: 'marketplace-api'
          port-placeholder: 'marketplace_port'

      - name: 'Check deployment - price'
        id: check-price-deployment
        uses: ./.github/actions/check-api-deployment
        with:
          service-name: 'price-api'
          port-placeholder: 'price_port'

      - name: 'Check deployment - stock'
        id: check-stock-deployment
        uses: ./.github/actions/check-api-deployment
        with:
          service-name: 'stock-api'
          port-placeholder: 'stock_port'

      - name: 'Check deployment - product'
        id: check-product-deployment
        uses: ./.github/actions/check-api-deployment
        with:
          service-name: 'product-api'
          port-placeholder: 'product_port'

      - name: 'Configure Bruno'
        uses: ./.github/actions/configure-bruno
        with:
          marketplace-port: ${{ steps.check-marketplace-deployment.outputs.public-port }}
          price-port: ${{ steps.check-price-deployment.outputs.public-port }}
          product-port: ${{ steps.check-product-deployment.outputs.public-port }}
          stock-port: ${{ steps.check-stock-deployment.outputs.public-port }}

      - uses: actions/setup-node@v4

      - name: 'Run tests'
        working-directory: ./api-tests
        run: |
          npm install
          npm run test:ci
