---
name: 'API tests'

on:
  workflow_dispatch:
  workflow_call:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: 'Build'
        working-directory: 'applications'
        run: ./mvnw clean package -DskipTests

      - name: 'Start apps'
        run: docker compose --env-file=./api-tests/.env.ci up --detach

      - name: 'tbd - marketplace'
        uses: ./.github/workflows/actions/check-api-deployment.yml
        with:
          service-name: 'marketplace-api'
          port-placeholder: 'marketplace_port'

      - name: 'tbd - price'
        uses: ./.github/workflows/actions/check-api-deployment.yml
        with:
          service-name: 'price-api'
          port-placeholder: 'price_port'

      - name: 'tbd - stock'
        uses: ./.github/workflows/actions/check-api-deployment.yml
        with:
          service-name: 'stock-api'
          port-placeholder: 'stock_port'

      - name: 'tbd - product'
        uses: ./.github/workflows/actions/check-api-deployment.yml
        with:
          service-name: 'product-api'
          port-placeholder: 'product_port'

      - uses: actions/setup-node@v4

      - name: 'Run tests'
        working-directory: ./api-tests
        run: |
          npm install
          npm run test:ci
