---
name: 'API tests'

on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Prepare build :
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: actions/setup-node@v4

      - name: 'Install Bruno cli'
        run: npm install -g @usebruno/cli

      # Start apps
      - name: 'Build'
        run: mvn clean package -DskipTests -f applications/pom.xml

      - name: 'Start apps'
        run: docker compose --env-file=./api-tests/.env.ci up --detach

      - name: 'Evaluate marketplace-api port'
        id: evaluate-marketplace-port
        uses: deroffal/github-actions/actions/docker/compose/evaluate-public-port@main
        with:
          service-name: 'marketplace-api'
          private-port: '8080'

      - name: 'Evaluate price-api port'
        id: evaluate-price-port
        uses: deroffal/github-actions/actions/docker/compose/evaluate-public-port@main
        with:
          service-name: 'price-api'
          private-port: '8080'

      - name: 'Evaluate product-api port'
        id: evaluate-product-port
        uses: deroffal/github-actions/actions/docker/compose/evaluate-public-port@main
        with:
          service-name: 'product-api'
          private-port: '8080'

      - name: 'Evaluate stock-api port'
        id: evaluate-stock-port
        uses: deroffal/github-actions/actions/docker/compose/evaluate-public-port@main
        with:
          service-name: 'stock-api'
          private-port: '8080'

      # Configure Bruno
      - name: 'Configure Bruno env'
        env:
          marketplace_port: ${{ steps.evaluate-marketplace-port.outputs.port }}
          price_port: ${{ steps.evaluate-price-port.outputs.port }}
          product_port: ${{ steps.evaluate-product-port.outputs.port }}
          stock_port: ${{ steps.evaluate-stock-port.outputs.port }}
        run: |
          sed -i 's/marketplace_port/${{ env.marketplace_port }}/g' ./api-tests/test.bru
          sed -i 's/price_port/${{ env.price_port }}/g' ./api-tests/test.bru
          sed -i 's/product_port/${{ env.product_port }}/g' ./api-tests/test.bru
          sed -i 's/stock_port/${{ env.stock_port }}/g' ./api-tests/test.bru

      - name: 'Copy configuration file'
        run: cp ./api-tests/test.bru ./client/eshop/environments/test.bru

      - name: 'Run tests'
        working-directory: ./client/eshop
        run: bru run . --env test
