---
name: Build project

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: '0 7 * * 1'

jobs:

  project-build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: deroffal/github-actions/.github/workflows/ci-maven.yml@main
    secrets: inherit
    with:
      working-directory: ./applications
      sonar-project-key: deroffal-github_eshop

