---
name: Build Java apps

on:
  workflow_dispatch:
  pull_request:
    paths:
      - applications/**
  push:
    branches:
      - main
    paths:
      - applications/**
  schedule:
    - cron: '0 7 * * 1'



jobs:
  project-build:
    permissions:
      contents: read
      actions: read
      checks: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-project-build
      cancel-in-progress: true
    uses: deroffal/github-actions/.github/workflows/ci-maven.yml@test-report
    secrets: inherit
    with:
      working-directory: ./applications
      java-version: 21
      java-distribution: 'temurin'
      sonar-project-key: 'deroffal-github_eshop'

  api-tests:
    permissions:
      contents: read
      actions: read
      checks: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-api-tests
      cancel-in-progress: true
    uses: ./.github/workflows/api-tests.yml
