---
name: Build Java apps

on:
  workflow_dispatch:
  pull_request:
    paths:
      - applications/**
  push:
    branches:
      - main
    paths:
      - applications/**
  schedule:
    - cron: '0 7 * * 1'

jobs:

  project-build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: deroffal/github-actions/.github/workflows/ci-maven.yml@main
    secrets: inherit
    with:
      working-directory: ./applications
      java-version: 21
      java-distribution: 'temurin'
      # skipping sonar for PR as it requires secret that won't be injected
      # (https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions)
      sonar-project-key: ${{ (github.event_name == 'pull_request' && 'deroffal-github_eshop') || ''}}

