name: build-docker

on:
  push:
    branches: [ main ]
    paths: [ applications ]
    
jobs:
  product-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./applications/k8s-lab.product-api
    
    steps:
      - name: Checkout branche
        uses: actions/checkout@master
          
      - name: Set up JDK
        uses: actions/setup-java@master
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Docker
        run: mvn -B spring-boot:build-image -DskipTests=true
        
      - name: Push to DockerHub
        run: |
            PROJECT_VERSION=${{ steps.get-version.outputs.PROJECT_VERSION }}
            docker tag deroffal/k8slab-productapi:latest deroffal/k8slab-productapi:${PROJECT_VERSION}
            docker push deroffal/k8slab-productapi:${PROJECT_VERSION}
            docker push deroffal/k8slab-productapi:latest
