name: build-docker

on:
  push:
    branches: [ main ]
    paths:
      - 'applications/**'
  workflow_dispatch:

jobs:

  version-job:
    runs-on: ubuntu-latest
    outputs:
      product-version: ${{ steps.evaluate-product.outputs.version }}
      stock-version: ${{ steps.evaluate-stock.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate product version
        working-directory: ./applications/k8s-lab.product-api
        id: evaluate-product
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Evaluate stock version
        working-directory: ./applications/k8s-lab.stock-api
        id: evaluate-stock
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  product-build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-product
      cancel-in-progress: true
    needs:
      - version-job
    uses: deroffal/github-actions/.github/workflows/build-maven-docker.yml@main
    secrets: inherit
    with:
      working-directory: ./applications/k8s-lab.product-api
      java-version: '17'
      java-distribution: 'adopt'
      image-name: 'deroffal/k8slab-productapi'
      tag-name: ${{ needs.version-job.outputs.product-version }}

  stock-build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-stock
      cancel-in-progress: true
    needs:
      - version-job
    uses: deroffal/github-actions/.github/workflows/build-maven-docker.yml@main
    secrets: inherit
    with:
      working-directory: ./applications/k8s-lab.stock-api
      java-version: '17'
      java-distribution: 'adopt'
      image-name: 'deroffal/k8slab-stockapi'
      tag-name: ${{ needs.version-job.outputs.stock-version }}
