name: Mutation testing

on:
  workflow_dispatch:
  push:
    paths:
      - 'applications/eshop-price/**'
    branch:
      - 'main'

jobs:

  mutation-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: deroffal/github-actions/actions/maven/mutation-testing@main
        with:
          working-directory: ./applications
          projects: eshop-price
