name: Release all APIs

on:
  workflow_dispatch:

jobs:
  evaluate-version:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-evaluate-version
      cancel-in-progress: true
    outputs:
      api-version: ${{ steps.evaluate-version.outputs.maven-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate version
        id: evaluate-version
        uses: deroffal/github-actions/actions/maven/evaluate-version@main
        with:
          working-directory: ./applications

  release:
    needs: evaluate-version
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.api }}
      cancel-in-progress: true
    strategy:
      matrix:
        api: [product, stock, price, marketplace]
    uses: deroffal/github-actions/.github/workflows/build-maven-docker-app.yml@main
    secrets: inherit
    with:
      working-directory: ./applications/eshop-${{ matrix.api }}
      build-method: 'dockerfile'
      java-version: 21
      java-distribution: 'temurin'
      image-name: 'deroffal/eshop-${{ matrix.api }}'
      tag-name: ${{ needs.evaluate-version.outputs.api-version }}
