name: Release all APIs

on:
  workflow_dispatch:

jobs:
  release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.api }}
      cancel-in-progress: true
    strategy:
      matrix:
        api: [product, stock, price, marketplace]
    uses: ./.github/workflows/release-api.yml
    secrets: inherit
    with:
      api-name: ${{ matrix.api }}
