name: Release an API

on:
  workflow_call:
    inputs:
      api-name:
        required: true
        type: string
        description: name of the api to release.

jobs:

  evaluate-version:
    runs-on: ubuntu-latest
    outputs:
      api-version: ${{ steps.evaluate-version.outputs.maven-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate version
        id: evaluate-version
        uses: deroffal/github-actions/actions/maven/evaluate-version@main
        with:
          working-directory: ./applications/eshop-${{ inputs.api-name }}

  release-api:
    needs:
      - evaluate-version
    uses: deroffal/github-actions/.github/workflows/build-maven-docker-app.yml@main
    secrets: inherit
    with:
      working-directory: ./applications/eshop-${{ inputs.api-name }}
      build-method: 'dockerfile'
      java-version: 21
      java-distribution: 'temurin'
      image-name: 'deroffal/eshop-${{ inputs.api-name }}'
      tag-name: ${{ needs.evaluate-version.outputs.api-version }}
