name: Release all APIs

on:
  workflow_dispatch:

jobs:

  product-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-product
      cancel-in-progress: true
    uses: ./.github/workflows/release-api.yml
    secrets: inherit
    with:
      api-name: 'product'

  stock-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-stock
      cancel-in-progress: true
    uses: ./.github/workflows/release-api.yml
    secrets: inherit
    with:
      api-name: 'stock'

  price-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-price
      cancel-in-progress: true
    uses: ./.github/workflows/release-api.yml
    secrets: inherit
    with:
      api-name: 'price'
