name: Release all APIs

on:
  workflow_dispatch:

jobs:
  evaluate-version:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-evaluate-version
      cancel-in-progress: true
    outputs:
      api-version: ${{ steps.evaluate-version.outputs.maven-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate version
        id: evaluate-version
        uses: deroffal/github-actions/actions/maven/evaluate-version@main
        with:
          working-directory: ./applications

  release:
    needs: evaluate-version
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.api }}
      cancel-in-progress: true
    strategy:
      matrix:
        api: [product, stock, price, marketplace]
    steps:
      - uses: actions/checkout@v4

      - name: 'Build with Maven'
        uses: deroffal/github-actions/actions/maven/build@main
        with:
          working-directory: ./applications
          java-version: 21
          java-distribution: 'temurin'
          projects: ':eshop-${{ matrix.api }}'

      - name: 'Build and push Docker image'
        uses: deroffal/github-actions/actions/docker/build-and-push@main
        with:
          working-directory: ./applications/eshop-${{ matrix.api }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          build-method: 'dockerfile'
          image-name: 'deroffal/eshop-${{ matrix.api }}'
          tag-name: ${{ needs.evaluate-version.outputs.api-version }}
